# Default values for mlflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: larribas/mlflow
  pullPolicy: IfNotPresent
  tag: latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
extraLabels: {}
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []

mlflow:
  oidc:
    enabled: false
    config: ""
    imports: ""
  replicas: 1
  postgres:
    create: true
    instanceID: ""
    hostname: ""
    port: 5432
    database: mlflow
    user: ""
    password: ""
  extraConfig: ""
  configMountPath: "/app/pythonpath"
  containerPort: 8088
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

extraConfigmapData: {}
