apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
data:
  {{- if .Values.mlflow.oidc.enabled}}
  oidc_client_secrets.json: |-
{{ .Values.mlflow.oidc.client_secrets | indent 4 }}
  {{- end}}

{{- if .Values.mlflow.oidc.enabled}}
  {{ .Values.mlflow.oidc.config | nindent 4 }}
{{- end }}
{{ .Values.mlflow.extraConfig | nindent 4 }}
{{- if .Values.extraConfigmapData}}
{{- toYaml .Values.extraConfigmapData | nindent 2 }}
{{- end }}
