{{ if .Values.mlflow.postgres.databaseEnabled }}
apiVersion: postgresql.org/v1
kind: PostgresDatabase
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  dbName: {{ .Values.mlflow.postgres.database }}
  dbRoleName: {{ .Values.mlflow.postgres.user }}
  dbRolePassword: {{ .Values.mlflow.postgres.password }}
  dbInstanceId: {{ .Values.mlflow.postgres.instanceID }}
{{ end }}