apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  {{- if not .Values.mlflow.autoscaling.enabled }}
  replicas: {{ .Values.mlflow.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [
              "mlflow",
              "server",
              "--host", "0.0.0.0",
              "--backend-store-uri", "postgresql+psycopg2://{{ include "mlflow.postgres.uri" . }}?user={{ .Values.mlflow.postgres.user }}&password={{ .Values.mlflow.postgres.password }}"
          ]
          envFrom:
            - secretRef:
                name: {{ include "mlflow.fullname" . }}
          volumeMounts:
            - name: "{{ include "mlflow.fullname" . }}-backend"
              mountPath: {{ .Values.mlflow.configMountPath | quote }}
              readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.mlflow.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 2
            failureThreshold: 6
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 6
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.mlflow.resources | nindent 12 }}
      {{- with .Values.mlflow.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mlflow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mlflow.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "mlflow.fullname" . }}
          configMap:
            name: {{ include "mlflow.fullname" . }}
