apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  dbRoleName: {{ .Values.mlflow.postgres.user | b64enc | quote }}
  dbRolePassword: {{ .Values.mlflow.postgres.password | b64enc | quote }}
