apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mlflow.postgres.username  }}
  DB_USERNAME: {{.Values.mlflow.postgres.username | b64enc }}
  {{- end }}
  {{- if .Values.mlflow.postgres.password }}
  DB_PASSWORD: {{.Values.mlflow.postgres.password | b64enc }}
  {{- end }}
